.travis.ymllanguage: node_js
node_js: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master

cache:
  directories:
  - node_modules

install:
- npm install

before_script:
- npm run fetch

script:
- npm run build

branches:
  only:
  - master

env:
  global:
  - GH_REF: github.com/EHDFE/ehdfe-weekly.git

